In [ ]:
def alter(file, dict_str_old_new):
    """
    替换文件中的字符串
    :param file:文件名
    :param old_str:就字符串
    :param new_str:新字符串
    :return:
    
    """
    file_data = ""
    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            for old_str, new_str in dict_str_old_new.items():
                if old_str in line:
                    print(line)
                    line = new_str
            file_data += line
    with open(file,"w",encoding="utf-8") as f:
        f.write(file_data)



In [ ]:
dict_str_old_new = { 'd':'f', 'g':'j'}

In [ ]:
for old_str, new_str in dict_str_old_new.items():
    print(old_str,new_str)

In [ ]:
dict_str_old_new = dict()
num_nodes=4
cpus_per_node=5
gpus_per_cpu=6

str_num_nodes = "#SBATCH --nodes=" + str(num_nodes) + "\n"
dict_str_old_new["#SBATCH --nodes="] = str_num_nodes

str_cpus_per_node = "#SBATCH --ntasks-per-node=" + str(cpus_per_node) + "\n"
dict_str_old_new["#SBATCH --ntasks-per-node="] = str_cpus_per_node

str_gpus_per_cpu = "#SBATCH --gres=gpu:" + str(gpus_per_cpu) + "\n"
dict_str_old_new["#SBATCH --gres=gpu:"] = str_gpus_per_cpu

alter("cycslurmjob.sh", dict_str_old_new)

In [30]:
import os
import tempfile

fp = tempfile.NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
fp.write(f"import os\nimport numpy\nprint('fuck')\n")     # 向该零时文件中写入一些数据

fp.seek(0) # 从文件中读取数据
print(fp.read())

f=os.popen("python " + fp.name)
print(f.read())



import os
import numpy
print('fuck')

fuck



In [ ]:
a="import os\nimport numpy\nprint('fuck')\n"

In [ ]:
with open("abcdefg.py","w",encoding="utf-8") as f:
    f.write(a)

In [ ]:
fp.name

In [ ]:
fp.read()

In [ ]:
fp.close()

In [ ]:
from tempfile import NamedTemporaryFile
 
with NamedTemporaryFile('w+t') as f:
    print('filename is:', f.name)
    ...
 
# File automatically destroyed

In [ ]:
!python abc.py

In [ ]:
os.system('vivado -jou {cdir}/vivado.jou -log {cdir}/vivado.log '
                       '-mode batch -source '
                       '{cfile}'.format(cdir=self.compile_dir, cfile=tcl_file))

In [ ]:
'{cdir}''{cfile}'.format(cdir='./', cfile='../')

In [ ]:
os.system('vivado')

In [31]:
a = "Submitted batch job 143"
int(a.replace("Submitted batch job ", ""))

143

In [35]:
a = "Submitted batch job 143"

In [36]:
a.split("Submitted batch job ")[1]

'143'

In [ ]:
if s1.startswith(s2):
    s3 = s1.replace(s2, '')

In [17]:
    from tempfile import NamedTemporaryFile
    def generate_slurm_job_file():

        str_num_nodes = f"#SBATCH --nodes=" + str(5) + f"\n"
        str_cpus_per_node = f"#SBATCH --ntasks-per-node=" + str(6) + f"\n"
        str_gpus_per_cpu = f"#SBATCH --gres=gpu:" + str(7) + f"\n"
        
        file_data = f""
        file_data += f"#!/bin/bash\n"
        file_data += "#SBATCH -o job.%j.out\n"
        file_data += "#SBATCH --partition=p40\n"
        file_data += "#SBATCH -J myFirstJob\n"
        file_data += str_num_nodes
        file_data += str_cpus_per_node
        file_data += str_gpus_per_cpu
        file_data += "cd /raid/slurm-for-quantum/home/qc01/cyc/TeD-Q/tedq/distributed_worker/\n"
        file_data += "rank=$(($SLURM_PROCID+1))\n"
        file_data += "srun python rpc_workers.py --num_nodes 2 --rank $rank --gpus_per_cpu 4 --cpus_per_node 1 --master_addr 172.17.224.177\n"


        fp = NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
        fp.write(file_data)     # 向该零时文件中写入一些数据
        print(fp.read())

        return fp

In [18]:
a = generate_slurm_job_file()

In [19]:
a

In [20]:
a.name

'/tmp/tmpashfh8ff'

In [21]:
a.read()

''

In [24]:
        str_num_nodes = "#SBATCH --nodes=" + str(5) + "\n"
        str_cpus_per_node = "#SBATCH --ntasks-per-node=" + str(6) + "\n"
        str_gpus_per_cpu = "#SBATCH --gres=gpu:" + str(7) + "\n"
        
        file_data = ""
        file_data += "#!/bin/bash\n"
        file_data += "#SBATCH -o job.%j.out\n"
        file_data += "#SBATCH --partition=p40\n"
        file_data += "#SBATCH -J myFirstJob\n"
        file_data += str_num_nodes
        file_data += str_cpus_per_node
        file_data += str_gpus_per_cpu
        file_data += "cd /raid/slurm-for-quantum/home/qc01/cyc/TeD-Q/tedq/distributed_worker/\n"
        file_data += "rank=$(($SLURM_PROCID+1))\n"
        file_data += "srun python rpc_workers.py --num_nodes 2 --rank $rank --gpus_per_cpu 4 --cpus_per_node 1 --master_addr 172.17.224.177\n"


        fp = NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
        fp.write(file_data)     # 向该零时文件中写入一些数据
        fp.write(f"fuck")
        print(fp.read())

In [25]:
fp.read()

''

In [45]:
def a(**kwargs):
    _a(**kwargs)

In [46]:
def _a(**kwargs):
    print(kwargs)

In [47]:
a(b=1, c=2)

{'b': 1, 'c': 2}


In [3]:
import pennylane as qml

In [10]:
    >>> dev = qml.device("default.qubit", wires=(0, 1))
    >>> @qml.qnode(dev)
    ... def circuit():
    ...     return qml.state()

In [11]:
circuit()

tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], requires_grad=True)

In [13]:
import tedq as qai
import numpy as np

In [15]:
g_matrix = np.array([[0., 0.], [0., 1.]], dtype=np.complex64)

In [18]:
qai.Unitary(matrix=g_matrix, qubits=[0], do_queue=False)

In [20]:
a=qml.Projector(np.array([1, 1]), wires=(0,1))

In [36]:
a.matrix()

array([[ 0.,  0.,  0.,  0.],
       [ 0., -0.,  0., -0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -1.]])

In [23]:
        g_matrix = np.array(
            [
            [0., 0., 0., 0.], 
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 1.],
            ], dtype=np.complex64)
        g_matrix = g_matrix.reshape([2,2,2,2])

In [25]:
g_matrix

array([[[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]]],


       [[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]]]], dtype=complex64)

In [34]:
a=qml.Projector(np.array([1]), wires=0) @ qml.PauliZ(1)

In [35]:
np.array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])