In [ ]:
def alter(file, dict_str_old_new):
    """
    替换文件中的字符串
    :param file:文件名
    :param old_str:就字符串
    :param new_str:新字符串
    :return:
    
    """
    file_data = ""
    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            for old_str, new_str in dict_str_old_new.items():
                if old_str in line:
                    print(line)
                    line = new_str
            file_data += line
    with open(file,"w",encoding="utf-8") as f:
        f.write(file_data)



In [ ]:
dict_str_old_new = { 'd':'f', 'g':'j'}

In [ ]:
for old_str, new_str in dict_str_old_new.items():
    print(old_str,new_str)

In [ ]:
dict_str_old_new = dict()
num_nodes=4
cpus_per_node=5
gpus_per_cpu=6

str_num_nodes = "#SBATCH --nodes=" + str(num_nodes) + "\n"
dict_str_old_new["#SBATCH --nodes="] = str_num_nodes

str_cpus_per_node = "#SBATCH --ntasks-per-node=" + str(cpus_per_node) + "\n"
dict_str_old_new["#SBATCH --ntasks-per-node="] = str_cpus_per_node

str_gpus_per_cpu = "#SBATCH --gres=gpu:" + str(gpus_per_cpu) + "\n"
dict_str_old_new["#SBATCH --gres=gpu:"] = str_gpus_per_cpu

alter("cycslurmjob.sh", dict_str_old_new)

In [30]:
import os
import tempfile

fp = tempfile.NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
fp.write(f"import os\nimport numpy\nprint('fuck')\n")     # 向该零时文件中写入一些数据

fp.seek(0) # 从文件中读取数据
print(fp.read())

f=os.popen("python " + fp.name)
print(f.read())



import os
import numpy
print('fuck')

fuck



In [ ]:
a="import os\nimport numpy\nprint('fuck')\n"

In [ ]:
with open("abcdefg.py","w",encoding="utf-8") as f:
    f.write(a)

In [ ]:
fp.name

In [ ]:
fp.read()

In [ ]:
fp.close()

In [ ]:
from tempfile import NamedTemporaryFile
 
with NamedTemporaryFile('w+t') as f:
    print('filename is:', f.name)
    ...
 
# File automatically destroyed

In [ ]:
!python abc.py

In [ ]:
os.system('vivado -jou {cdir}/vivado.jou -log {cdir}/vivado.log '
                       '-mode batch -source '
                       '{cfile}'.format(cdir=self.compile_dir, cfile=tcl_file))

In [ ]:
'{cdir}''{cfile}'.format(cdir='./', cfile='../')

In [ ]:
os.system('vivado')

In [31]:
a = "Submitted batch job 143"
int(a.replace("Submitted batch job ", ""))

143

In [35]:
a = "Submitted batch job 143"

In [36]:
a.split("Submitted batch job ")[1]

'143'

In [ ]:
if s1.startswith(s2):
    s3 = s1.replace(s2, '')

In [17]:
    from tempfile import NamedTemporaryFile
    def generate_slurm_job_file():

        str_num_nodes = f"#SBATCH --nodes=" + str(5) + f"\n"
        str_cpus_per_node = f"#SBATCH --ntasks-per-node=" + str(6) + f"\n"
        str_gpus_per_cpu = f"#SBATCH --gres=gpu:" + str(7) + f"\n"
        
        file_data = f""
        file_data += f"#!/bin/bash\n"
        file_data += "#SBATCH -o job.%j.out\n"
        file_data += "#SBATCH --partition=p40\n"
        file_data += "#SBATCH -J myFirstJob\n"
        file_data += str_num_nodes
        file_data += str_cpus_per_node
        file_data += str_gpus_per_cpu
        file_data += "cd /raid/slurm-for-quantum/home/qc01/cyc/TeD-Q/tedq/distributed_worker/\n"
        file_data += "rank=$(($SLURM_PROCID+1))\n"
        file_data += "srun python rpc_workers.py --num_nodes 2 --rank $rank --gpus_per_cpu 4 --cpus_per_node 1 --master_addr 172.17.224.177\n"


        fp = NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
        fp.write(file_data)     # 向该零时文件中写入一些数据
        print(fp.read())

        return fp

In [18]:
a = generate_slurm_job_file()

In [19]:
a

In [20]:
a.name

'/tmp/tmpashfh8ff'

In [21]:
a.read()

''

In [24]:
        str_num_nodes = "#SBATCH --nodes=" + str(5) + "\n"
        str_cpus_per_node = "#SBATCH --ntasks-per-node=" + str(6) + "\n"
        str_gpus_per_cpu = "#SBATCH --gres=gpu:" + str(7) + "\n"
        
        file_data = ""
        file_data += "#!/bin/bash\n"
        file_data += "#SBATCH -o job.%j.out\n"
        file_data += "#SBATCH --partition=p40\n"
        file_data += "#SBATCH -J myFirstJob\n"
        file_data += str_num_nodes
        file_data += str_cpus_per_node
        file_data += str_gpus_per_cpu
        file_data += "cd /raid/slurm-for-quantum/home/qc01/cyc/TeD-Q/tedq/distributed_worker/\n"
        file_data += "rank=$(($SLURM_PROCID+1))\n"
        file_data += "srun python rpc_workers.py --num_nodes 2 --rank $rank --gpus_per_cpu 4 --cpus_per_node 1 --master_addr 172.17.224.177\n"


        fp = NamedTemporaryFile(mode='w+t', encoding="utf-8", newline='\n') # 创建一个临时文件
        fp.write(file_data)     # 向该零时文件中写入一些数据
        fp.write(f"fuck")
        print(fp.read())

In [25]:
fp.read()

''

In [45]:
def a(**kwargs):
    _a(**kwargs)

In [46]:
def _a(**kwargs):
    print(kwargs)

In [47]:
a(b=1, c=2)

{'b': 1, 'c': 2}


In [3]:
import pennylane as qml

In [10]:
    >>> dev = qml.device("default.qubit", wires=(0, 1))
    >>> @qml.qnode(dev)
    ... def circuit():
    ...     return qml.state()

In [11]:
circuit()

tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], requires_grad=True)

In [13]:
import tedq as qai
import numpy as np

In [15]:
g_matrix = np.array([[0., 0.], [0., 1.]], dtype=np.complex64)

In [18]:
qai.Unitary(matrix=g_matrix, qubits=[0], do_queue=False)

In [20]:
a=qml.Projector(np.array([1, 1]), wires=(0,1))

In [36]:
a.matrix()

array([[ 0.,  0.,  0.,  0.],
       [ 0., -0.,  0., -0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -1.]])

In [23]:
        g_matrix = np.array(
            [
            [0., 0., 0., 0.], 
            [0., 0., 0., 0.],
            [0., 0., 0., 0.],
            [0., 0., 0., 1.],
            ], dtype=np.complex64)
        g_matrix = g_matrix.reshape([2,2,2,2])

In [25]:
g_matrix

array([[[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]]],


       [[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]]]], dtype=complex64)

In [34]:
a=qml.Projector(np.array([1]), wires=0) @ qml.PauliZ(1)

In [35]:
np.array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [9]:
import torch
from torch import Tensor
from torch.optim.optimizer import (Optimizer, required, _use_grad_for_differentiable, _default_to_fused_or_foreach,
                        _differentiable_doc, _foreach_doc, _maximize_doc)
from typing import List, Optional
from torch.utils._foreach_utils import _group_tensors_by_device_and_dtype

__all__ = ['SGD', 'sgd']

class SGD(Optimizer):
    def __init__(self, params, lr=required, momentum=0, dampening=0,
                 weight_decay=0, nesterov=False, *, maximize: bool = False, foreach: Optional[bool] = None,
                 differentiable: bool = False):
        if lr is not required and lr < 0.0:
            raise ValueError("Invalid learning rate: {}".format(lr))
        if momentum < 0.0:
            raise ValueError("Invalid momentum value: {}".format(momentum))
        if weight_decay < 0.0:
            raise ValueError("Invalid weight_decay value: {}".format(weight_decay))

        defaults = dict(lr=lr, momentum=momentum, dampening=dampening,
                        weight_decay=weight_decay, nesterov=nesterov,
                        maximize=maximize, foreach=foreach,
                        differentiable=differentiable)
        if nesterov and (momentum <= 0 or dampening != 0):
            raise ValueError("Nesterov momentum requires a momentum and zero dampening")
        super().__init__(params, defaults)

    def __setstate__(self, state):
        super().__setstate__(state)
        for group in self.param_groups:
            group.setdefault('nesterov', False)
            group.setdefault('maximize', False)
            group.setdefault('foreach', None)
            group.setdefault('differentiable', False)

    def _init_group(self, group, params_with_grad, d_p_list, momentum_buffer_list):
        has_sparse_grad = False

        for p in group['params']:
            if p.grad is not None:
                params_with_grad.append(p)
                d_p_list.append(p.grad)
                if p.grad.is_sparse:
                    has_sparse_grad = True

                state = self.state[p]
                if 'momentum_buffer' not in state:
                    momentum_buffer_list.append(None)
                else:
                    momentum_buffer_list.append(state['momentum_buffer'])

        return has_sparse_grad


    @_use_grad_for_differentiable
    def step(self, closure=None):
        """Performs a single optimization step.
        Args:
            closure (Callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            params_with_grad = []
            d_p_list = []
            momentum_buffer_list = []

            has_sparse_grad = self._init_group(group, params_with_grad, d_p_list, momentum_buffer_list)

            sgd(params_with_grad,
                d_p_list,
                momentum_buffer_list,
                weight_decay=group['weight_decay'],
                momentum=group['momentum'],
                lr=group['lr'],
                dampening=group['dampening'],
                nesterov=group['nesterov'],
                maximize=group['maximize'],
                has_sparse_grad=has_sparse_grad,
                foreach=group['foreach'])

            # update momentum_buffers in state
            for p, momentum_buffer in zip(params_with_grad, momentum_buffer_list):
                state = self.state[p]
                state['momentum_buffer'] = momentum_buffer

        return loss


SGD.__doc__ = r"""\
    Implements stochastic gradient descent (optionally with momentum).
    .. math::
       \begin{aligned}
            &\rule{110mm}{0.4pt}                                                                 \\
            &\textbf{input}      : \gamma \text{ (lr)}, \: \theta_0 \text{ (params)}, \: f(\theta)
                \text{ (objective)}, \: \lambda \text{ (weight decay)},                          \\
            &\hspace{13mm} \:\mu \text{ (momentum)}, \:\tau \text{ (dampening)},
            \:\textit{ nesterov,}\:\textit{ maximize}                                     \\[-1.ex]
            &\rule{110mm}{0.4pt}                                                                 \\
            &\textbf{for} \: t=1 \: \textbf{to} \: \ldots \: \textbf{do}                         \\
            &\hspace{5mm}g_t           \leftarrow   \nabla_{\theta} f_t (\theta_{t-1})           \\
            &\hspace{5mm}\textbf{if} \: \lambda \neq 0                                           \\
            &\hspace{10mm} g_t \leftarrow g_t + \lambda  \theta_{t-1}                            \\
            &\hspace{5mm}\textbf{if} \: \mu \neq 0                                               \\
            &\hspace{10mm}\textbf{if} \: t > 1                                                   \\
            &\hspace{15mm} \textbf{b}_t \leftarrow \mu \textbf{b}_{t-1} + (1-\tau) g_t           \\
            &\hspace{10mm}\textbf{else}                                                          \\
            &\hspace{15mm} \textbf{b}_t \leftarrow g_t                                           \\
            &\hspace{10mm}\textbf{if} \: \textit{nesterov}                                       \\
            &\hspace{15mm} g_t \leftarrow g_{t} + \mu \textbf{b}_t                             \\
            &\hspace{10mm}\textbf{else}                                                   \\[-1.ex]
            &\hspace{15mm} g_t  \leftarrow  \textbf{b}_t                                         \\
            &\hspace{5mm}\textbf{if} \: \textit{maximize}                                          \\
            &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} + \gamma g_t                   \\[-1.ex]
            &\hspace{5mm}\textbf{else}                                                    \\[-1.ex]
            &\hspace{10mm}\theta_t \leftarrow \theta_{t-1} - \gamma g_t                   \\[-1.ex]
            &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
            &\bf{return} \:  \theta_t                                                     \\[-1.ex]
            &\rule{110mm}{0.4pt}                                                          \\[-1.ex]
       \end{aligned}
    Nesterov momentum is based on the formula from
    `On the importance of initialization and momentum in deep learning`__.
    """ + r"""
    Args:
        params (iterable): iterable of parameters to optimize or dicts defining
            parameter groups
        lr (float): learning rate
        momentum (float, optional): momentum factor (default: 0)
        weight_decay (float, optional): weight decay (L2 penalty) (default: 0)
        dampening (float, optional): dampening for momentum (default: 0)
        nesterov (bool, optional): enables Nesterov momentum (default: False)
        {maximize}
        {foreach}
        {differentiable}
    """.format(maximize=_maximize_doc, foreach=_foreach_doc, differentiable=_differentiable_doc) + r"""
    Example:
        >>> # xdoctest: +SKIP
        >>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
        >>> optimizer.zero_grad()
        >>> loss_fn(model(input), target).backward()
        >>> optimizer.step()
    __ http://www.cs.toronto.edu/%7Ehinton/absps/momentum.pdf
    .. note::
        The implementation of SGD with Momentum/Nesterov subtly differs from
        Sutskever et. al. and implementations in some other frameworks.
        Considering the specific case of Momentum, the update can be written as
        .. math::
            \begin{aligned}
                v_{t+1} & = \mu * v_{t} + g_{t+1}, \\
                p_{t+1} & = p_{t} - \text{lr} * v_{t+1},
            \end{aligned}
        where :math:`p`, :math:`g`, :math:`v` and :math:`\mu` denote the
        parameters, gradient, velocity, and momentum respectively.
        This is in contrast to Sutskever et. al. and
        other frameworks which employ an update of the form
        .. math::
            \begin{aligned}
                v_{t+1} & = \mu * v_{t} + \text{lr} * g_{t+1}, \\
                p_{t+1} & = p_{t} - v_{t+1}.
            \end{aligned}
        The Nesterov version is analogously modified.
        Moreover, the initial value of the momentum buffer is set to the
        gradient value at the first step. This is in contrast to some other
        frameworks that initialize it to all zeros.
    """


def sgd(params: List[Tensor],
        d_p_list: List[Tensor],
        momentum_buffer_list: List[Optional[Tensor]],
        # kwonly args with defaults are not supported by functions compiled with torchscript issue #70627
        # setting this as kwarg for now as functional API is compiled by torch/distributed/optim
        has_sparse_grad: bool = None,
        foreach: Optional[bool] = None,
        *,
        weight_decay: float,
        momentum: float,
        lr: float,
        dampening: float,
        nesterov: bool,
        maximize: bool):
    r"""Functional API that performs SGD algorithm computation.
    See :class:`~torch.optim.SGD` for details.
    """

    if foreach is None:
        # why must we be explicit about an if statement for torch.jit.is_scripting here?
        # because JIT can't handle Optionals nor fancy conditionals when scripting
        if not torch.jit.is_scripting():
            _, foreach = _default_to_fused_or_foreach(params, differentiable=False, use_fused=False)
        else:
            foreach = False

    if foreach and torch.jit.is_scripting():
        raise RuntimeError('torch.jit.script not supported with foreach optimizers')

    if foreach and not torch.jit.is_scripting():
        func = _multi_tensor_sgd
    else:
        func = _single_tensor_sgd

    func(params,
         d_p_list,
         momentum_buffer_list,
         weight_decay=weight_decay,
         momentum=momentum,
         lr=lr,
         dampening=dampening,
         nesterov=nesterov,
         has_sparse_grad=has_sparse_grad,
         maximize=maximize)

def _single_tensor_sgd(params: List[Tensor],
                       d_p_list: List[Tensor],
                       momentum_buffer_list: List[Optional[Tensor]],
                       *,
                       weight_decay: float,
                       momentum: float,
                       lr: float,
                       dampening: float,
                       nesterov: bool,
                       maximize: bool,
                       has_sparse_grad: bool):

    for i, param in enumerate(params):
        d_p = d_p_list[i] if not maximize else -d_p_list[i]

        if weight_decay != 0:
            d_p = d_p.add(param, alpha=weight_decay)

        if momentum != 0:
            buf = momentum_buffer_list[i]

            if buf is None:
                buf = torch.clone(d_p).detach()
                momentum_buffer_list[i] = buf
            else:
                buf.mul_(momentum).add_(d_p, alpha=1 - dampening)

            if nesterov:
                d_p = d_p.add(buf, alpha=momentum)
            else:
                d_p = buf

        param.add_(d_p, alpha=-lr)


def _multi_tensor_sgd(params: List[Tensor],
                      grads: List[Tensor],
                      momentum_buffer_list: List[Optional[Tensor]],
                      *,
                      weight_decay: float,
                      momentum: float,
                      lr: float,
                      dampening: float,
                      nesterov: bool,
                      maximize: bool,
                      has_sparse_grad: bool):

    if len(params) == 0:
        return

    grouped_tensors = _group_tensors_by_device_and_dtype([params, grads, momentum_buffer_list], with_indices=True)
    for device_params, device_grads, device_momentum_buffer_list, indices in grouped_tensors.values():
        device_has_sparse_grad = any(grad.is_sparse for grad in device_grads)

        if maximize:
            device_grads = torch._foreach_neg(tuple(device_grads))  # type: ignore[assignment]

        if weight_decay != 0:
            device_grads = torch._foreach_add(device_grads, device_params, alpha=weight_decay)

        if momentum != 0:
            bufs = []

            all_states_with_momentum_buffer = True
            for i in range(len(device_momentum_buffer_list)):
                if device_momentum_buffer_list[i] is None:
                    all_states_with_momentum_buffer = False
                    break
                else:
                    bufs.append(device_momentum_buffer_list[i])

            if all_states_with_momentum_buffer:
                torch._foreach_mul_(bufs, momentum)
                torch._foreach_add_(bufs, device_grads, alpha=1 - dampening)
            else:
                bufs = []
                for i in range(len(device_momentum_buffer_list)):
                    if device_momentum_buffer_list[i] is None:
                        buf = device_momentum_buffer_list[i] = momentum_buffer_list[indices[i]] = \
                            torch.clone(device_grads[i]).detach()
                    else:
                        buf = device_momentum_buffer_list[i]
                        buf.mul_(momentum).add_(device_grads[i], alpha=1 - dampening)

                    bufs.append(buf)

            if nesterov:
                torch._foreach_add_(device_grads, bufs, alpha=momentum)
            else:
                device_grads = bufs

        if not device_has_sparse_grad:
            torch._foreach_add_(device_params, device_grads, alpha=-lr)
        else:
            # foreach APIs don't support sparse
            for i in range(len(device_params)):
                device_params[i].add_(device_grads[i], alpha=-lr)

ImportError: cannot import name '_default_to_fused_or_foreach' from 'torch.optim.optimizer' (/home/cyc/anaconda3/envs/cycenv/lib/python3.8/site-packages/torch/optim/optimizer.py)

In [8]:
from torch.optim import optimizer

In [11]:
from torch.optim import SGD as sgd

In [13]:
class abc(sgd):
    pass
    

In [19]:
a = torch.tensor([4.])
abc([a], lr=0.3)

abc (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.3
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [88]:
import torch
from torch.optim.optimizer import Optimizer, required

class SGD(Optimizer):
    def __init__(self, params, lr=required, momentum=0, dampening=0,
                 weight_decay1=0, weight_decay2=0, nesterov=False):
        print(params)
        defaults = dict(lr=lr, momentum=momentum, dampening=dampening,
                        weight_decay1=weight_decay1, weight_decay2=weight_decay2, nesterov=nesterov)
        if nesterov and (momentum <= 0 or dampening != 0):
            raise ValueError("Nesterov momentum requires a momentum and zero dampening")
        super(SGD, self).__init__(params, defaults)

    def __setstate__(self, state):
        super(SGD, self).__setstate__(state)
        for group in self.param_groups:
            group.setdefault('nesterov', False)

    def step(self, metric_tensor, closure=None):
        """Performs a single optimization step.

        Arguments:
            closure (callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            weight_decay1 = group['weight_decay1']
            weight_decay2 = group['weight_decay2']
            momentum = group['momentum']
            dampening = group['dampening']
            nesterov = group['nesterov']
            

            d_p_list = []
            p_list = []
            for p in group['params']:
                print(p)
                if p.grad is None:
                    continue
                d_p = p.grad.data
                if weight_decay1 != 0:
                    d_p.add_(weight_decay1, torch.sign(p.data))
                if weight_decay2 != 0:
                    d_p.add_(weight_decay2, p.data)
                if momentum != 0:
                    param_state = self.state[p]
                    if 'momentum_buffer' not in param_state:
                        buf = param_state['momentum_buffer'] = torch.zeros_like(p.data)
                        buf.mul_(momentum).add_(d_p)
                    else:
                        buf = param_state['momentum_buffer']
                        buf.mul_(momentum).add_(1 - dampening, d_p)
                    if nesterov:
                        d_p = d_p.add(momentum, buf)
                    else:
                        d_p = buf

                #p.data.add_(-group['lr'], d_p)
                p_list.append(p)
                d_p_list.append(d_p)
            
            print(p_list, d_p_list)
            grad_flat = torch.tensor(d_p_list)
            x_flat = torch.tensor(p_list)
            stepsize = group['lr']
            
            x_new_flat = x_flat - stepsize * torch.linalg.solve(metric_tensor, grad_flat)
            print(x_new_flat)
            
            for i, p in enumerate(group['params']):
                p.data = x_new_flat[i].data
                

        return loss


In [89]:
metric_tensor = torch.tensor([[1., 0.], [0., 1.]])

In [90]:
a = [torch.tensor([4.], requires_grad=True), torch.tensor([2.], requires_grad=True)]

In [91]:
c = torch.sum(a[0]+a[1])

In [92]:
c.backward()

In [93]:
b = SGD(a, lr = 0.1)

[tensor([4.], requires_grad=True), tensor([2.], requires_grad=True)]


In [98]:
b.step(metric_tensor)

tensor(3.8000, requires_grad=True)
tensor(1.8000, requires_grad=True)
[tensor(3.8000, requires_grad=True), tensor(1.8000, requires_grad=True)] [tensor([1.]), tensor([1.])]
tensor([3.7000, 1.7000])


In [99]:
a

[tensor(3.7000, requires_grad=True), tensor(1.7000, requires_grad=True)]