In [ ]:
import pennylane as qml
from pennylane import numpy as np

dev = qml.device("default.qubit", wires=3)


@qml.qnode(dev)
def circuit(params):
    # |psi_0>: state preparation
    qml.RY(np.pi / 4, wires=0)
    qml.RY(np.pi / 3, wires=1)
    qml.RY(np.pi / 7, wires=2)

    # V0(theta0, theta1): Parametrized layer 0
    qml.RZ(params[0], wires=0)
    qml.RZ(params[1], wires=1)

    # W1: non-parametrized gates
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])

    # V_1(theta2, theta3): Parametrized layer 1
    qml.RY(params[2], wires=1)
    qml.RX(params[3], wires=2)

    # W2: non-parametrized gates
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])

    return qml.expval(qml.PauliY(0))


params = np.array([0.432, -0.123, 0.543, 0.233])

In [ ]:
circuit(params)

In [ ]:
steps = 200
init_params = np.array([0.432, -0.123, 0.543, 0.233], requires_grad=True)

In [ ]:
type(init_params)

In [ ]:
dcircuit = qml.grad(circuit)

In [ ]:
dcircuit(theta)

In [ ]:
@qml.qnode(dev)
def circuit(params):
    qml.PauliX(0)
    qml.PauliX(1)
    # |psi_0>: state preparation
    qml.RY(np.pi / 4, wires=0)
    qml.RY(np.pi / 3, wires=1)
    qml.RY(np.pi / 7, wires=2)

    # V0(theta0, theta1): Parametrized layer 0
    qml.RZ(params[0], wires=0)
    qml.RZ(params[1], wires=1)

    # W1: non-parametrized gates
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])

    # V_1(theta2, theta3): Parametrized layer 1
    qml.RY(params[2], wires=1)
    qml.RX(params[3], wires=2)

    # W2: non-parametrized gates
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])

    return qml.expval(qml.PauliY(0))
    #return [qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1))]

In [ ]:
circuit(theta)

In [ ]:
dcircuit = qml.grad(circuit)

In [ ]:
dcircuit(theta)

In [ ]:
gd_cost = []
opt = qml.GradientDescentOptimizer(0.01)

theta = init_params
for _ in range(steps):
    theta = opt.step(circuit, theta)
    gd_cost.append(circuit(theta))


In [ ]:
%time
qng_cost = []
opt = qml.QNGOptimizer(0.01)

theta = init_params
for _ in range(steps):
    theta = opt.step(circuit, theta)
    qng_cost.append(circuit(theta))

In [ ]:
from matplotlib import pyplot as plt

plt.style.use("seaborn")
plt.plot(gd_cost, "b", label="Vanilla gradient descent")
plt.plot(qng_cost, "g", label="Quantum natural gradient descent")

plt.ylabel("Cost function value")
plt.xlabel("Optimization steps")
plt.legend()
plt.show()

In [ ]:
import torch
a = torch.tensor([1.], requires_grad=True)

In [ ]:
b = torch.tensor([1.], requires_grad=True)

In [ ]:
c = a-1j*b

In [ ]:
c = (a*b)**2

In [ ]:
c

In [ ]:
d = torch.norm(a)

In [ ]:
d = torch.dot(c.conj(), c)
d = d.real
d

In [ ]:
d.backward()

In [ ]:
a.grad

In [ ]:
b.grad

In [ ]:
d.dtype

In [ ]:
c

In [ ]:
torch.abs(c)

In [ ]:
torch.norm(c)

In [ ]:
c.real

In [ ]:
_EINSUM_SYMBOLS_BASE = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

def circuit_tensor():
    
	qubitss = [[0, 3], [6, 9], [4, 3]]

	einsum_str = ''
	all_qubits = []
	for qubits in qubitss:
		einsum_str += ''.join(tuple(_EINSUM_SYMBOLS_BASE[i] for i in qubits))
		einsum_str += ','
		all_qubits.extend(qubits)

	all_qubits = list(set(all_qubits))
	all_qubits.sort()

	einsum_str = einsum_str[0:-2]
	einsum_str += '->'
	einsum_str += ''.join(tuple(_EINSUM_SYMBOLS_BASE[i] for i in all_qubits))
	print(einsum_str)

In [ ]:
circuit_tensor()

In [1]:
import tedq as qai
import numpy as np

In [2]:
qai.circuit_tensor

<function tedq.QInterpreter.circuits.circuit_tensor.circuit_tensor(func, *params)>

In [11]:
def circuitDef(params):
    # |psi_0>: state preparation
    #qai.RY(np.pi / 4, qubits=[0], trainable_params=[])
    #qai.RY(np.pi / 3, qubits=[1], trainable_params=[])
    #qai.RY(np.pi / 7, qubits=[2], trainable_params=[])

    # V0(theta0, theta1): Parametrized layer 0
    qai.PauliX(qubits=[0])
    #qai.RZ(params[0], qubits=[0])
    #qai.RZ(params[1], qubits=[1])

    # W1: non-parametrized gates
    #qai.CNOT(qubits=[0, 1])
    #qai.CNOT(qubits=[1, 2])

    # V_1(theta2, theta3): Parametrized layer 1
    #qai.RY(params[2], qubits=[1])
    #qai.RX(params[3], qubits=[2])

    # W2: non-parametrized gates
    #qai.CNOT(qubits=[0, 1])
    #qai.CNOT(qubits=[1, 2])

    #return qai.expval(qai.PauliY(qubits=[0]))


params = (4., 5., 6., 7.)

In [12]:
qai.circuit_tensor(circuitDef, params)

[[0]]
ba->ba
(array([[0, 1],
       [1, 0]]),)
[[0 1]
 [1 0]]


array([[0, 1],
       [1, 0]])

In [5]:
a = [1, 4, 6]
a.index(4)

1

In [6]:
''.join(tuple(a))

TypeError: sequence item 0: expected str instance, int found

In [ ]:
list(reverse(a))