In [1]:
import sys
sys.path.append('..')
import tedq as qai

import pennylane as qml

# Related package
import torch
import numpy as np
import matplotlib.pyplot as plt
import time

import gpytorch


# Hamiltonian related
from openfermion.chem import MolecularData
import openfermion
from openfermionpyscf import run_pyscf

# MISC
r_bohr = 0.529177210903

# Global variable
n_qubits = 4
n_layers = 3
n_search = 500
n_experts = 5

# 
tolerance = 1e-6
min_pass = 5

# Set molecule parameters.
basis = 'sto-3g'
multiplicity = 1
n_points = 40
bond_length_interval = 3.0 / n_points

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


In [2]:
import itertools


valid_Rs =  [qai.RY, qai.RZ]
valid_CNOTs = ([0, 1], [1, 2], [2, 3])

Rs_space = list(itertools.product(valid_Rs, valid_Rs, valid_Rs, valid_Rs))
CNOTs_space = [[y for y in CNOTs if y is not None] for CNOTs in list(itertools.product(*([x, None] for x in valid_CNOTs)))]
NAS_search_space = list(itertools.product(Rs_space, CNOTs_space))

In [3]:
len(NAS_search_space)

128

In [4]:
NAS_search_space[3][1]

[[0, 1]]

In [5]:
def Rot(alpha, beta, theta, qubit):
    qml.RX(alpha, wires=qubit)
    qml.RY(beta, wires=qubit)
    qml.RZ(theta, wires=qubit)
# Ansatz
def ansatz(params):
    for i in range(n_qubits):
        Rot(params[i][0], params[i][1], params[i][2], i)
    for j in range(n_qubits-1, -1, -1):
        for k in range(j+1, n_qubits):
            qml.CNOT(wires=[j, k])

In [6]:
# Hamiltonian


def get_H2_hamiltonian(distance):
    bond_length=distance*r_bohr
    geometry = [('H', (0., 0., -bond_length/2)), ('H', (0., 0., bond_length/2))]
    molecule = MolecularData(
        geometry, basis, multiplicity,charge=0,
        description=str(round(bond_length, 2)))
    molecule = run_pyscf(molecule,run_scf=1,run_fci=1)
    terms_molecular_hamiltonian = molecule.get_molecular_hamiltonian(occupied_indices=[], active_indices=[0,1])
    fermionic_hamiltonian = openfermion.transforms.get_fermion_operator(terms_molecular_hamiltonian)
    jw_hamiltonian = openfermion.transforms.jordan_wigner(fermionic_hamiltonian)
#     print(jw_hamiltonian.terms)
#     print('Hartree-Fock energy of {} Hartree.'.format(molecule.hf_energy))
#     print('Hartree-Fock energy of {} Hartree.'.format(molecule.fci_energy))

    return jw_hamiltonian.terms, molecule.fci_energy


In [7]:
AIdList = []

# Ansatz

def ansatz(params, AIdList):
    for i, Aid in enumerate(AIdList):
        for j in range(n_qubits):
            NAS_search_space[Aid][0][j](params[i][j], qubits=[j])
        for cnot_pair in NAS_search_space[Aid][1]:
            qai.CNOT(qubits=list(cnot_pair))

In [8]:

def getGateFromName(name):
    if name=="I":
        return qai.I
    if name=="X":
        return qai.PauliX
    if name=="Y":
        return qai.PauliY
    if name=="Z":
        return qai.PauliZ
def measurements(gatesPrefix):
    gateList = []
    for qubit, gatePrefix in list(gatesPrefix):
        gate = getGateFromName(gatePrefix)
        gateList.append(gate(qubits=[qubit]))
    return gateList

def initCircuit(distance, selectedAIdList):
    AIdList = selectedAIdList
    H, fci_energy = get_H2_hamiltonian(distance)
    for idx in H:
        def circuitDef(params):
            ansatz(params, AIdList)
            qai.measurement.expval(measurements(idx))
        circList.append(qai.Circuit(circuitDef, n_qubits, torch.zeros(n_layers,n_qubits)))
        compiledCircList.append(circList[-1].compilecircuit('pytorch', print_output=False))
        weightList.append(H[idx])
    return fci_energy


In [9]:
def expert_evaluator(model, subnet, n_experts, cost_fn):

    target_expert = 0
    target_loss = None
    for i in range(n_experts):
        model.params = model.get_params(subnet, i)
        temp_loss = cost_fn(model.params)
        if target_loss is None or temp_loss < target_loss:
            target_loss = temp_loss
            target_expert = i
    return target_expert

In [10]:
class CircuitSearchModel():
    def __init__(self, n_qubits=4, n_layers=3, n_experts=5):
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        self.n_experts = n_experts
        '''init params'''
        # randomly initialize parameters from a normal distribution
        self.params_space = np.random.uniform(0, np.pi * 2, (n_experts, n_layers, len(Rs_space), n_qubits))
        self.params = torch.ones((3,4), requires_grad=True)
    
    def get_params(self, subnet, expert_idx):
        self.subnet = subnet
        self.expert_idx = expert_idx
        params = []
        # print("CNOT", NAS_search_space)
        # print("get", subnet, expert_idx)
        for j in range(self.n_layers):
            r_idx = subnet[j] // len(CNOTs_space)
            params.append(self.params_space[expert_idx, j, r_idx:r_idx+1])
#         print("get param", params, np.concatenate(params, axis=0))
        self.params=torch.tensor(params, requires_grad=True)
        return np.concatenate(params, axis=0)

    def set_params(self):
        self.params = self.params.cpu().detach().numpy()
        for j in range(self.n_layers):
            r_idx = self.subnet[j] // len(CNOTs_space)
            # print("set", j, self.subnet[j], r_idx, len(CNOTs_space))
            # print("set", self.params_space)
            self.params_space[self.expert_idx, j, r_idx:r_idx+1] = self.params[j, :]

    def __call__(self, params, wires):
        circuit_search(params, wires=wires,
                       n_qubits=self.n_qubits,
                       n_layers=self.n_layers,
                       arch=self.subnet)

In [11]:
import torch.nn as nn

distList = np.arange(0.5,1.0, 0.5)
energyList = np.array([])
timeList = np.array([])
fciEnergyList = np.array([])
modelParam = CircuitSearchModel()

timestamp = np.array([])
error = np.array([])

distance = 1.2



In [12]:
step_size = 0.2


time_start=time.time()    


for i_iter in range(n_search):
    circList = []
    compiledCircList = []
    weightList = []
    selectedAIdList = np.random.randint(0, len(NAS_search_space), (n_layers,)).tolist()
    
    fciE = initCircuit(distance, selectedAIdList)
    
#     find optimal expert
    expert_idx = np.random.randint(n_experts)
    if i_iter>100:
        for i in range(n_experts):
            # get params
            min_loss = 100000
            min_expert_id = 0
            params = modelParam.get_params(selectedAIdList, i)
#             print("params",params)
            # calculate
            exp = 0
            for idx, compiledCirc in enumerate(compiledCircList):   
#                 print("compile idx ", idx)
                exp += compiledCirc(modelParam.params).real*weightList[idx].real
            loss = exp
            if loss<min_loss:
                min_loss = loss
                min_expert_id = i
        expert_idx = min_expert_id
    # get params
    modelParam.get_params(selectedAIdList, expert_idx)
#     params = torch.zeros((3,4))
    vNgdOpt = gpytorch.optim.NGD([modelParam.params], num_data=1, lr=0.1)
    
    # for each set
    l_sum = 0
    loss = nn.L1Loss()
    exp = 0
    for idx, compiledCirc in enumerate(compiledCircList):   
        exp += compiledCirc(modelParam.params).real*weightList[idx].real


    l = loss(exp, torch.Tensor([-100.]))
    l.backward()        
#     optimizer.step()
#     optimizer.zero_grad()
#     params = opt.step(cost, params)
#     print("old", modelParam.params)
    vNgdOpt.step()
#     print("new", modelParam.params)
#     print("grad", modelParam.params.grad)
    vNgdOpt.zero_grad()

    # set params
    modelParam.set_params()
        
        
#     print(params)
    print(i_iter, selectedAIdList, fciE, exp.item())
    energyList = np.append(energyList, exp.item())
    timeList = np.append(timeList, time.time()-time_start)
    fciEnergyList = np.append(fciEnergyList, fciE)
time_end=time.time()

/var/folders/45/8c2bcn7n3ln498zczt81kn9c0000gp/T/ipykernel_70411/4090894739.py:21: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:204.)
  self.params=torch.tensor(params, requires_grad=True)


0 [69, 118, 20] -1.1266988216513705 0.2514457404613495
1 [82, 101, 57] -1.1266988216513705 0.4698590934276581
2 [84, 13, 68] -1.1266988216513705 0.5829383730888367
3 [24, 99, 29] -1.1266988216513705 0.06856957077980042
4 [102, 65, 72] -1.1266988216513705 -0.22568930685520172
5 [41, 70, 68] -1.1266988216513705 0.48540639877319336
6 [62, 107, 8] -1.1266988216513705 0.5406479835510254
7 [45, 8, 117] -1.1266988216513705 -0.2472575157880783
8 [44, 36, 15] -1.1266988216513705 -0.3995998203754425
9 [115, 113, 71] -1.1266988216513705 0.21514521539211273
10 [32, 92, 21] -1.1266988216513705 0.3580686151981354
11 [83, 29, 26] -1.1266988216513705 0.3822665214538574
12 [126, 80, 38] -1.1266988216513705 0.10344864428043365
13 [66, 53, 50] -1.1266988216513705 0.6490551829338074
14 [85, 106, 127] -1.1266988216513705 -0.3903382122516632
15 [108, 47, 20] -1.1266988216513705 0.28957754373550415
16 [60, 50, 39] -1.1266988216513705 0.7226638197898865
17 [44, 65, 6] -1.1266988216513705 -0.2958071231842041
1

compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.82531919e+00 9.74054996e-01 8.38973460e-01 3.40012443e-03]
 [1.03845545e+00 4.66864915e+00 2.82627336e+00 1.77784552e+00]
 [5.84712655e+00 3.83975939e+00 4.72032901e-01 3.91733978e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
102 [24, 79, 60] -1.1266988216513705 -0.21896561980247498
params [[0.89235825 1.893167   1.17211904 3.77248992]
 [5.85252338 6.12760989 3.30432126 5.79418275]
 [0.15873839 2.71823637 2.25890065 5.10106676]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.55772771 1.75451878 1.47549959 4.62748958]
 [0.37572025 5.800

params [[0.89235825 1.893167   1.17211904 3.77248992]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [6.16888444 3.28034821 3.16365742 1.69612754]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.55772771 1.75451878 1.47549959 4.62748958]
 [2.18131759 2.67023542 4.96170103 3.33464334]
 [0.84609589 0.59320011 0.32089823 2.10399036]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.41484896 5.81017969 4.96128876 3.96512901]
 [6.18916581 5.33483929 5.56555244 3.53468423]
 [3.0523582  3.63209088 4.16891389 5.28560278]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

111 [111, 8, 72] -1.1266988216513705 0.3188846707344055
params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [0.25026207 2.94688677 2.95941977 4.32380585]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [4.63980694 1.79035835 3.31562889 0.2373397 ]
 [4.15299062 0.55274867 5.63218349 1.4206322 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.06309249 2.95239971 4.5173062  4.01746009]
 [4.36026928 2.48855582 3.71162322 4.1747455 ]
 [3.14341332 3.90662681 5.8108552  5.61153647]]
compile idx  0
compile idx  1
compile

params [[1.28657142 4.73269727 5.99701539 0.65244213]
 [3.1111288  1.14045179 0.03007676 4.60130684]
 [3.11238097 6.11119891 2.50276903 1.46772736]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.58965882 3.73747271 5.86542513 0.12849095]
 [1.48508116 2.12338563 4.11615336 2.70432161]
 [1.19017184 6.07958899 1.52181696 0.30246565]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.15920192 4.61084521 1.14964055 2.63707368]
 [6.11304879 0.39961096 5.56631646 5.21481023]
 [4.45439971 5.16110565 2.52695708 4.66496916]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

121 [69, 106, 62] -1.1266988216513705 0.01246117427945137
params [[5.36916885 1.6329528  3.58385397 0.46652324]
 [3.1111288  1.14045179 0.03007676 4.60130684]
 [3.11238097 6.11119891 2.50276903 1.46772736]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.48205241 1.18130164 1.21427589 5.09712425]
 [1.48508116 2.12338563 4.11615336 2.70432161]
 [1.19017184 6.07958899 1.52181696 0.30246565]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.59335877 1.82227796 5.14312818 3.5916573 ]
 [6.11304879 0.39961096 5.56631646 5.21481023]
 [4.45439971 5.16110565 2.52695708 4.66496916]]
compile idx  0
compile idx  1
compi

compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [5.26213073 0.22270974 4.75766728 0.28292722]
 [1.73680491 4.97824416 3.81225584 3.96514792]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.46044251 5.91996136 1.17844108 4.75165948]
 [1.02914585 2.74994251 5.62945978 1.31520377]
 [3.62943938 3.07319625 4.03729431 5.5178673 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.68242157 1.16185472 4.64692927 6.09696031]
 [2.717251   5.44067094 1.48104014 0.63517066]
 [0.14132255 3.07593166 1.35745241 2.37946107]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
co

params [[5.36916885 1.6329528  3.58385397 0.46652324]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [3.11182169 5.41227336 3.73849836 3.59912006]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.48205241 1.18130164 1.21427589 5.09712425]
 [2.96556476 0.94388754 1.9479378  4.78167822]
 [4.15163706 1.47786216 2.97141058 0.53413758]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.59335877 1.82227796 5.14312818 3.5916573 ]
 [3.40082399 4.6935263  2.08191394 5.25056208]
 [3.75311676 2.59363717 5.24921443 1.83963873]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.88886042 4.29796045 5.48784522 3.87658955]
 [0.88616092 4.48611571 2.34592989 1.38775785]
 [6.17427113 6.1028404  2.65046689 0.15993636]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.75125027 4.86611848 2.94717808 2.65170625]
 [6.11252804 3.71430355 5.03774154 2.76630673]
 [3.81934533 4.65617059 1.31164924 6.08102923]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
135 [7, 111, 120] -1.1266988216513705 -0.2672035694122314

compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.76173682 4.86754945 2.95435551 2.65826604]
 [3.1264939  4.50143146 3.09139119 0.63091914]
 [0.38124343 5.93424268 3.37845814 3.3482366 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
139 [5, 99, 72] -1.1266988216513705 -0.3291268050670624
params [[1.28657142 4.73269727 5.99701539 0.65244213]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [3.75283648 0.75047522 4.41083007 5.11111794]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.58965

params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [4.16057529 1.03282824 2.30567109 3.4630745 ]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [1.63221901 3.9593408  6.19642805 3.58682179]
 [3.83375937 5.71536015 3.84436226 2.45871601]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.06309249 2.95239971 4.5173062  4.01746009]
 [3.71934638 4.09230749 6.17541032 4.72587427]
 [3.5814475  1.45168104 2.71965649 0.34466785]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

params [[4.88229093 0.00833769 0.49201262 1.2684216 ]
 [1.42269405 1.78772324 0.37271495 3.27017254]
 [2.19221544 4.28064048 0.52445136 4.99827593]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.74159921 1.53292479 6.02222411 6.15021749]
 [3.42413971 5.89394541 3.68209228 1.09862559]
 [5.57425276 5.53648529 3.67321946 0.74586939]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
148 [114, 122, 101] -1.1266988216513705 0.4946092963218689
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [4.92114009 5.1348117  2.52972092 1.65682695]]
compile idx  0
compile idx  1
comp

152 [5, 96, 80] -1.1266988216513705 -0.24276798963546753
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [0.15873839 2.71823637 2.25890065 5.10106676]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.21540448 1.3186405  0.67613799]
 [2.96556476 0.94388754 1.9479378  4.78167822]
 [1.41118722 0.71818225 5.22712437 5.51923401]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.64037201 1.05537117 0.2641654  4.97044201]
 [3.40082399 4.6935263  2.08191394 5.25056208]
 [1.60943166 1.19349819 1.39022042 4.84195896]]
compile idx  0
compile idx  1
compil

157 [90, 102, 102] -1.1266988216513705 -0.2956874370574951
params [[2.51098470e+00 4.91422470e+00 2.23074953e+00 2.76197628e+00]
 [4.34692351e+00 7.62355649e-01 3.20048510e-03 5.24158970e+00]
 [5.87650540e+00 2.24096124e+00 4.95505926e+00 3.47958760e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1973005  4.0921528  5.90633896 4.76829576]
 [3.09466628 3.54396713 3.15872794 2.01695136]
 [2.85667058 4.74914008 2.52549028 1.49536456]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.48047652 4.71504842 2.38779447 4.69031967]
 [2.20795826 4.58118069 4.22337054 2.18803133]
 [4.24862294 2.48044144 1.64776048

162 [74, 20, 58] -1.1266988216513705 -0.25410231947898865
params [[6.03535539 0.73909115 0.761497   2.19503837]
 [5.85252338 6.12760989 3.30432126 5.79418275]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [0.37572025 5.8002601  6.22909289 3.53268177]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [3.26974172 0.36442387 0.13511342 0.2252376 ]
 [4.60807758 0.60954928 2.36621432 0.29325912]]
compile idx  0
compile idx  1
compi

167 [3, 43, 29] -1.1266988216513705 0.34585100412368774
params [[6.03535539 0.73909115 0.761497   2.19503837]
 [3.52353542 4.73996881 2.41288737 0.45927031]
 [6.16888444 3.28034821 3.16365742 1.69612754]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [1.60834656 1.95780191 6.18775983 5.91680718]
 [0.84609589 0.59320011 0.32089823 2.10399036]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [0.62882466 2.54340928 5.7294358  4.43363858]
 [3.0523582  3.63209088 4.16891389 5.28560278]]
compile idx  0
compile idx  1
compile

compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
172 [59, 63, 92] -1.1266988216513705 0.5328401923179626
params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [2.70653491 4.74562709 0.09483786 0.81274254]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [3.85960056 6.17976677 0.37452829 3.13812537]
 [2.86398214 6.25767298 4.33461876 5.53181041]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
com

compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.06554936 5.61931127 1.45424141 2.91888744]
 [1.13570331 3.39985913 5.85023584 2.08960737]
 [5.57425276 5.53648529 3.66134591 0.7369538 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
177 [81, 52, 99] -1.1266988216513705 0.2205457091331482
params [[1.91232691 5.96177492 2.55025771 2.75035733]
 [5.85252338 6.12760989 3.30432126 5.79418275]
 [1.27913256 1.98143733 0.14805772 2.01577153]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
p

params [[6.03535539 0.73909115 0.761497   2.19503837]
 [1.72712976 4.17218169 0.73744722 3.51887316]
 [3.11182169 5.41227336 3.73849836 3.59912006]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [1.81545532 4.51012288 2.77162834 5.18088257]
 [4.15163706 1.47786216 2.97141058 0.53413758]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [1.79820417 5.06964262 3.14188814 4.46316092]
 [3.75311676 2.59363717 5.24921443 1.83963873]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
186 [90, 85, 2] -1.1266988216513705 0.5034512877464294
params [[6.14826127 4.32295969 3.19142255 1.12130555]
 [6.21397639 1.49357638 1.14539921 0.55384765]
 [2.70653491 4.74562709 0.09483786 0.81274254]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [5.26213073 0.22270974 4.75766728 0.28292722]
 [2.86398214 6.25767298 4.33461876 5.53181041]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.46044251 5.91996136 1.17844108 4.75165948]
 [1.02914585 2.74994251 5.62945978 1.31520377]
 [3.14

compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.75636196 0.74209197 1.0211571  1.75306849]
 [0.88616092 4.48611571 2.34592989 1.38775785]
 [5.35479219 4.69692246 5.98375365 5.28236469]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.29903133 4.68751565 1.93567297 4.46463014]
 [6.11252804 3.71430355 5.06323099 2.76630673]
 [3.92731861 5.66460313 0.32261803 4.28113688]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
191 [22, 109, 7] -1.1266988216513705 -0.21099288761615753
params [[5.95087289 6.19015765 5.06337812 0.62134475]
 [1.5309624  4.68151591 4.30385005 

195 [118, 77, 37] -1.1266988216513705 0.0045562684535980225
params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [5.20900451 1.09784455 6.09006705 0.77064595]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1973005  4.0921528  5.90633896 4.76829576]
 [3.85960056 6.17976677 0.37452829 3.13812537]
 [5.35085572 2.1391693  3.16238524 5.51478088]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.48047652 4.71504842 2.38779447 4.69031967]
 [0.53368208 2.26815573 0.85584838 3.36783596]
 [5.60711248 2.52696248 4.93246252 1.41159713]]
compile idx  0
compile idx  1
com

compile idx  14
200 [26, 19, 63] -1.1266988216513705 0.6043409109115601
params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [6.21397639 1.49357638 1.14539921 0.55384765]
 [1.27913256 1.98143733 0.14805772 2.01577153]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [5.26213073 0.22270974 4.75766728 0.28292722]
 [1.73680491 4.97824416 3.81225584 3.96514792]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.06309249 2.95239971 4.5173062  4.01746009]
 [1.02914585 2.74994251 5.62945978 1.31520377]
 [3.62943938 3.07319625 4.03729431 5.5178673 ]]
compile idx  0
compil

compile idx  11
compile idx  12
compile idx  13
compile idx  14
205 [111, 114, 114] -1.1266988216513705 0.5951622128486633
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [1.72712976 4.17218169 0.73744722 3.51887316]
 [0.43593457 6.07704838 3.41790731 3.68830406]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.87734782 3.19153959 0.75216797 2.30672167]
 [1.81545532 4.51012288 2.77162834 5.18088257]
 [1.13757571 4.98918019 2.31260047 1.45899863]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.43535652 0.24566034 4.82266873 0.52870928]
 [1.79820417 5.06964262 3.14188814 4.46316092]
 [5.66388107 0.589

compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
210 [66, 44, 44] -1.1266988216513705 0.0436864048242569
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [2.64512358 5.10468301 1.38801571 0.50433468]
 [0.15873839 2.71823637 2.25890065 5.10106676]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.87734782 3.19153959 0.75216797 2.30672167]
 [2.21975174 4.90565054 0.75795775 5.44891102]
 [1.41118722 0.71818225 5.22712437 5.51923401]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
com

compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
215 [18, 5, 14] -1.1266988216513705 0.44015198945999146
params [[6.14826127 4.32295969 3.19142255 1.12130555]
 [2.36407973 4.34800089 1.32783767 5.21124303]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [3.33873875 2.52191196 2.50927297 4.14057524]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.46044251 5.91996136 1.17844108 4.75165948]
 [4.184

compile idx  14
220 [71, 107, 62] -1.1266988216513705 -0.022170761600136757
params [[5.57508271e-01 1.77447757e+00 4.62746621e+00 6.25525305e+00]
 [4.34692351e+00 7.62355649e-01 3.20048510e-03 5.24158970e+00]
 [5.87650540e+00 2.24096124e+00 4.95505926e+00 3.47958760e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.60699844 3.48444363 6.09566836 5.46289143]
 [3.09466628 3.54396713 3.15872794 2.01695136]
 [2.85667058 4.74914008 2.52549028 1.49536456]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.61457559 2.75415836 5.61734708 3.82912095]
 [2.20795826 4.58118069 4.22337054 2.18803133]
 [4.24862294 2.48

compile idx  11
compile idx  12
compile idx  13
compile idx  14
225 [67, 78, 54] -1.1266988216513705 -0.03740096837282181
params [[2.51098470e+00 4.91422470e+00 2.23074953e+00 2.76197628e+00]
 [4.34692351e+00 7.62355649e-01 3.20048510e-03 5.24158970e+00]
 [3.11182169e+00 5.41227336e+00 3.73849836e+00 3.59912006e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1973005  4.0921528  5.90633896 4.76829576]
 [3.09466628 3.54396713 3.15872794 2.01695136]
 [4.15163706 1.47786216 2.97141058 0.53413758]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.48047652 4.71504842 2.38779447 4.69031967]
 [2.20795826 4.581

compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
230 [97, 84, 100] -1.1266988216513705 0.7109470963478088
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.21540448 1.3186405  0.67613799]
 [2.96556476 0.94388754 1.9479378  4.78167822]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.64037201 1.05537117 0.2641654  4.9

compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
235 [98, 30, 43] -1.1266988216513705 -0.17856857180595398
params [[1.91232691 5.96177492 2.55025771 2.75035733]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.35283173 3.36105291 5.05474221 1.83821781]
 [4.63980694 1.79035835 3.31562889 0.2373397 ]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.46161387 3.1573419  1.4312198  3.33879488]
 [4.36026928 2.48855

compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
240 [6, 38, 66] -1.1266988216513705 0.7272629141807556
params [[5.95087289 6.19015765 5.06337812 0.62134475]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.1194543  2.76264174 3.9911714  1.30011499]
 [2.18131759 2.67023542 4.96170103 3.33464334]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.03591412 1.20647325 3.81393125 4.05768845]
 [6.18916581 5.33483929 5.56555244 3.5

compile idx  13
compile idx  14
245 [105, 97, 13] -1.1266988216513705 0.06680878251791
params [[6.14826127 4.32295969 3.19142255 1.12130555]
 [2.64512358 5.10468301 1.38801571 0.50433468]
 [5.80594762 1.78058054 5.08035728 3.53359869]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [2.21975174 4.90565054 0.75795775 5.44891102]
 [0.16351821 3.1249786  5.45783491 6.13489142]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.46044251 5.91996136 1.17844108 4.75165948]
 [4.68038335 3.1393667  1.03151664 0.43103713]
 [3.0967637  1.90003811 3.98215087 3.88592476]]
compil

compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
250 [102, 23, 51] -1.1266988216513705 -0.05049466714262962
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.21540448 1.3186405  0.67613799]
 [5.32866803 6.04604118 3.72130409 3.82690966]
 [3.83375937 5.71536015 3.84436226 2.45871601]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.64037201 1.05537117 0.2641654  4.97044201]
 [2.

compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.67349289 2.59433691 0.38918909 3.90441104]
 [3.37850653 5.86047126 3.6019086  0.32554849]
 [0.6710613  5.07531504 5.55548813 3.5449945 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
255 [14, 115, 42] -1.1266988216513705 -0.2340240776538849
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [3.52353542 4.73996881 2.41288737 0.45927031]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.2154044

259 [106, 125, 58] -1.1266988216513705 0.6760189533233643
params [[1.28657142 4.73269727 5.99701539 0.65244213]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [4.92114009 5.1348117  2.52972092 1.65682695]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.58965882 3.73747271 5.86542513 0.12849095]
 [3.85960056 6.17976677 0.37452829 3.13812537]
 [2.50716341 2.41555589 2.63491166 2.72566515]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.15920192 4.61084521 1.14964055 2.63707368]
 [0.53368208 2.26815573 0.85584838 3.36783596]
 [1.67617174 6.21961944 1.19478772 3.00333829]]
compile idx  0
compile idx  1
compi

compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
264 [23, 78, 43] -1.1266988216513705 -0.04460068792104721
params [[4.59017543 3.36203427 5.68665682 5.51941278]
 [0.66452493 0.04733511 2.66576474 3.28841585]
 [5.80594762 1.78058054 5.08035728 3.53359869]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.2615441  0.52737739 5.82704784 0.97012081]
 [5.96571498 4.53394149 2.05942221 2.66301848]
 [0.16351821 3.1249786  5.45783491 6.13489142]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.66071012 1.90303514 1.46742141 5.32885808]
 [0.09730553 4.73754181 0.9074644  2.69028961]
 [3

compile idx  14
269 [78, 95, 12] -1.1266988216513705 0.15142878890037537
params [[0.55750827 1.77447757 4.62746621 6.25525305]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [2.70653491 4.74562709 0.09483786 0.81274254]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.60699844 3.48444363 6.09566836 5.46289143]
 [5.32866803 6.04604118 3.72130409 3.82690966]
 [2.86398214 6.25767298 4.33461876 5.53181041]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.61457559 2.75415836 5.61734708 3.82912095]
 [2.59719601 1.3362253  4.27029789 6.02931344]
 [3.14107956 0.81331115 0.83460287 2.57323576]]
compile idx  0
compi

274 [103, 117, 4] -1.1266988216513705 -0.16010195016860962
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [2.64512358 5.10468301 1.38801571 0.50433468]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.21540448 1.3186405  0.67613799]
 [2.21975174 4.90565054 0.75795775 5.44891102]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.64037201 1.05537117 0.2641654  4.97044201]
 [4.68038335 3.1393667  1.03151664 0.43103713]
 [4.60807758 0.60954928 2.36621432 0.29325912]]
compile idx  0
compile idx  1
comp

params [[6.07078508 4.80175664 3.85988744 4.19295658]
 [2.05030584 1.99845524 1.98199519 1.21574287]
 [6.17427113 6.1028404  2.65046689 0.15993636]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.89641706 3.88179951 2.31695835 2.46669598]
 [0.84759629 5.03469672 3.53560982 1.43568082]
 [3.81934533 4.65617059 1.31164924 6.08102923]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
279 [95, 59, 123] -1.1266988216513705 -0.43424469232559204
params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
comp

compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
283 [80, 108, 42] -1.1266988216513705 0.41829249262809753
params [[0.55750827 1.77447757 4.62746621 6.25525305]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [5.80594762 1.78058054 5.08035728 3.53359869]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.60699844 3.48444363 6.09566836 5.46289143]
 [2.18131759 2.67023542 4.96170103 3.33464334]
 [0.16351821 3.1249786  5.45783491 6.13489142]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.61457559 2.75415836 5.61734708 3.82912095]
 [6.18916581 5.33483

compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [0.37572025 5.8002601  6.22909289 3.53268177]
 [4.15299062 0.55274867 5.63218349 1.4206322 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.06309249 2.95239971 4.5173062  4.01746009]
 [3.26974172 0.36442387 0.13511342 0.2252376 ]
 [3.14341332 3.90662681 5.8108552  5.61153647]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.15141421 0.81849292 3.37373702 0.34855704]
 [1.44002981 3.57809827 5.0218076

compile idx  13
compile idx  14
292 [20, 62, 37] -1.1266988216513705 -0.14471741020679474
params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1973005  4.0921528  5.90633896 4.76829576]
 [2.96556476 0.94388754 1.9479378  4.78167822]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.48047652 4.71504842 2.38779447 4.69031967]
 [3.40082399 4.6935263  2.08191394 5.25056208]
 [4.60807758 0.60954928 2.36621432 0.29325912]]
com

compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.3873029  4.63100346 1.91952467 2.26673043]
 [1.03845545 4.58185971 2.77229349 1.77784552]
 [5.69481656 3.83975939 0.4720329  3.91733978]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
297 [49, 78, 61] -1.1266988216513705 0.15256892144680023
params [[0.89235825 1.893167   1.17211904 3.77248992]
 [3.1111288  1.14045179 0.03007676 4.60130684]
 [3.75283648 0.75047522 4.41083007 5.11111794]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
co

301 [111, 103, 100] -1.1266988216513705 0.7006959319114685
params [[1.66444565 2.68774882 0.38866153 3.44284514]
 [3.1111288  1.14045179 0.03007676 4.60130684]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.5272134  4.43818284 1.00316574 5.84281865]
 [1.48508116 2.12338563 4.11615336 2.70432161]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.52446831 5.05097669 1.39611546 0.00991422]
 [6.11304879 0.39961096 5.56631646 5.21481023]
 [4.15557658 1.53675954 0.62502092 2.10135598]]
compile idx  0
compile idx  1
comp

306 [55, 53, 15] -1.1266988216513705 0.4039843678474426
params [[5.36916885 1.6329528  3.58385397 0.46652324]
 [0.66452493 0.04733511 2.66576474 3.28841585]
 [5.20900451 1.09784455 6.09006705 0.77064595]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.48205241 1.18130164 1.21427589 5.09712425]
 [5.96571498 4.53394149 2.05942221 2.66301848]
 [5.35085572 2.1391693  3.16238524 5.51478088]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.59335877 1.82227796 5.14312818 3.5916573 ]
 [0.09730553 4.73754181 0.9074644  2.69028961]
 [5.60711248 2.52696248 4.93246252 1.41159713]]
compile idx  0
compile idx  1
compile

compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
311 [94, 16, 3] -1.1266988216513705 0.3223170042037964
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [2.70653491 4.74562709 0.09483786 0.81274254]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.87734782 3.19153959 0.75216797 2.30672167]
 [3.85960056 6.17976677 0.37452829 3.13812537]
 [2.86398214 6.25767298 4.33461876 5.53181041]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.43535652 0.24566034 4.82266873 0.52870928]
 [0.53368208 2.26815573

compile idx  14
params [[0.62433143 2.66337226 0.3854809  3.90441104]
 [1.18737925 5.30258836 4.09078477 0.49260281]
 [1.11143794 4.59288688 1.39422848 3.73572936]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
316 [13, 15, 109] -1.1266988216513705 -0.5117703676223755
params [[6.14826127 4.32295969 3.19142255 1.12130555]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [5.32866803 6.04604118 3.72130409 3.82690966]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
comp

320 [63, 32, 24] -1.1266988216513705 0.5006488561630249
params [[6.03535539e+00 7.39091153e-01 7.61497002e-01 2.19503837e+00]
 [4.34692351e+00 7.62355649e-01 3.20048510e-03 5.24158970e+00]
 [5.87650540e+00 2.24096124e+00 4.95505926e+00 3.47958760e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [3.09466628 3.54396713 3.15872794 2.01695136]
 [2.85667058 4.74914008 2.52549028 1.49536456]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [2.20795826 4.58118069 4.22337054 2.18803133]
 [4.24862294 2.48044144 1.64776048 5.

compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.460995   4.12616656 1.66984468 3.57911778]
 [1.70406268 3.35070917 2.19181774 2.15879467]
 [3.19388096 4.94615978 3.64195449 1.95119788]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
325 [57, 66, 66] -1.1266988216513705 -0.10759584605693817
params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [0.15873839 2.71823637 2.25890065 5.10106676]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.197

compile idx  14
329 [9, 90, 74] -1.1266988216513705 -0.05275832861661911
params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [5.80594762 1.78058054 5.08035728 3.53359869]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.51691877 4.54154804 5.94395411 1.61060742]
 [2.18131759 2.67023542 4.96170103 3.33464334]
 [0.16351821 3.1249786  5.45783491 6.13489142]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.06309249 2.95239971 4.5173062  4.01746009]
 [6.18916581 5.33483929 5.56555244 3.53468423]
 [3.0967637  1.90003811 3.98215087 3.88592476]]
compile idx  0
compi

compile idx  14
params [[1.78916502 5.04190304 4.15926425 1.84175282]
 [2.77050999 2.5665664  4.98205924 4.12894685]
 [3.6857408  4.94213441 5.28040786 5.62599664]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.35083651 4.55164164 1.74204029 2.86202522]
 [2.40490082 3.27370903 5.61966349 3.67028399]
 [4.14845279 5.93912738 0.74125891 2.72965473]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
334 [44, 41, 18] -1.1266988216513705 0.06577053666114807
params [[0.55750827 1.77447757 4.62746621 6.25525305]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [5.8765054  2.24096124 4.95505926 3.4795876 ]]
compile idx  0
compi

params [[0.55750827 1.77447757 4.62746621 6.25525305]
 [0.66452493 0.04733511 2.66576474 3.28841585]
 [4.92114009 5.1348117  2.52972092 1.65682695]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.60699844 3.48444363 6.09566836 5.46289143]
 [5.96571498 4.53394149 2.05942221 2.66301848]
 [2.50716341 2.41555589 2.63491166 2.72566515]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.61457559 2.75415836 5.61734708 3.82912095]
 [0.09730553 4.73754181 0.9074644  2.69028961]
 [1.67617174 6.21961944 1.19478772 3.00333829]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.00522324 4.29063664 1.98941613 4.44710239]
 [3.1264939  4.50143146 3.10646737 0.52407975]
 [3.79464865 0.56776285 2.9756494  5.01958299]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
343 [65, 101, 52] -1.1266988216513705 -0.21433241665363312
params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [5.85252338 6.12760989 3.30432126 5.79418275]
 [4.92114009 5.1348117  2.52972092 1.65682695]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.19

params [[6.03535539 0.73909115 0.761497   2.19503837]
 [5.85252338 6.12760989 3.30432126 5.79418275]
 [3.75283648 0.75047522 4.41083007 5.11111794]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [0.37572025 5.8002601  6.22909289 3.53268177]
 [3.21507298 0.92226742 0.2516113  0.15129348]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [3.26974172 0.36442387 0.13511342 0.2252376 ]
 [2.03838363 2.02942567 2.67372052 0.13149753]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

params [[4.11477349 1.59052781 0.76848971 3.7547041 ]
 [4.76111095 4.8875444  0.39503528 0.88704144]
 [0.14132255 3.07593166 1.35745241 2.37946107]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.43040728 0.22425749 0.55658263 0.61167343]
 [1.15959213 3.39985913 5.85023584 2.08605763]
 [0.38124343 5.95020439 3.37489541 3.3482366 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
352 [110, 54, 74] -1.1266988216513705 0.332006573677063
params [[5.91467766 3.0447109  1.86598685 3.44796203]
 [2.36407973 4.34800089 1.32783767 5.21124303]
 [3.11182169 5.41227336 3.73849836 3.59912006]]
compile idx  0
compile idx  1
compile

compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
356 [105, 67, 89] -1.1266988216513705 0.3111659586429596
params [[6.03535539 0.73909115 0.761497   2.19503837]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [3.11238097 6.11119891 2.50276903 1.46772736]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.73467341 1.7948165  4.10425382 3.586262  ]
 [5.32866803 6.04604118 3.72130409 3.82690966]
 [1.19017184 6.07958899 1.52181696 0.30246565]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.67471898 5.90910071 0.49366153 2.57490994]
 [2.59719601 1.336225

compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
361 [62, 76, 122] -1.1266988216513705 -0.16739889979362488
params [[2.76587287 2.46936229 0.89711853 2.57998579]
 [6.21397639 1.49357638 1.14539921 0.55384765]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.19090005 1.21540448 1.3186405  0.67613799]
 [5.26213073 0.22270974 4.75766728 0.28292722]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.64037201 1.05537117 0.2641654  4.97044201]
 [1.02914585 2.74994251 5.62945978 1.31520377]
 [

compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1785656  0.442167   6.2068588  2.55553252]
 [0.96354439 5.03469672 3.53560982 1.43568082]
 [6.16756665 4.14534497 2.5504236  0.72121905]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
366 [98, 60, 13] -1.1266988216513705 -0.07411591708660126
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [5.8765054  2.24096124 4.95505926 3.4795876 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14

params [[6.14826127 4.32295969 3.19142255 1.12130555]
 [1.5309624  4.68151591 4.30385005 5.90567567]
 [5.20900451 1.09784455 6.09006705 0.77064595]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[6.09093133 2.99427537 6.09290174 5.76102837]
 [2.18131759 2.67023542 4.96170103 3.33464334]
 [5.35085572 2.1391693  3.16238524 5.51478088]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.46044251 5.91996136 1.17844108 4.75165948]
 [6.18916581 5.33483929 5.56555244 3.53468423]
 [5.60711248 2.52696248 4.93246252 1.41159713]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
375 [24, 4, 73] -1.1266988216513705 -0.02690611034631729
params [[3.06271978 2.59104643 6.00420722 4.57127542]
 [0.70546889 1.75407116 2.51156641 2.03524646]
 [0.49051635 0.78274256 2.25025553 2.49519767]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[4.36652678 3.80200633 5.82348794 1.08905158]
 [4.63980694 1.79035835 3.31562889 0.2373397 ]
 [2.95537497 5.4244639  0.19970223 1.76961714]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
com

compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
380 [125, 22, 8] -1.1266988216513705 0.16940847039222717
params [[5.36916885 1.6329528  3.58385397 0.46652324]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [0.25026207 2.94688677 2.95941977 4.32380585]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[3.48205241 1.18130164 1.21427589 5.09712425]
 [2.96556476 0.94388754 1.9479378  4.78167822]
 [4.15299062 0.55274867 5.63218349 1.4206322 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
co

385 [61, 95, 43] -1.1266988216513705 -0.1309804916381836
params [[1.28657142e+00 4.73269727e+00 5.99701539e+00 6.52442128e-01]
 [4.34692351e+00 7.62355649e-01 3.20048510e-03 5.24158970e+00]
 [9.90174715e-01 3.07995464e+00 1.64419564e+00 1.88512550e+00]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.58965882 3.73747271 5.86542513 0.12849095]
 [3.09466628 3.54396713 3.15872794 2.01695136]
 [3.83375937 5.71536015 3.84436226 2.45871601]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.15920192 4.61084521 1.14964055 2.63707368]
 [2.20795826 4.58118069 4.22337054 2.18803133]
 [3.5814475  1.45168104 2.71965649 0

compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.29126832 4.12616656 1.66984468 3.57911778]
 [2.44119513 3.27370903 5.59743761 3.67028399]
 [6.16118242 4.05918241 2.56290886 0.72121905]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
390 [56, 46, 15] -1.1266988216513705 -0.1464238315820694
params [[0.89235825 1.893167   1.17211904 3.77248992]
 [4.11338822 1.73310488 1.87495087 2.57538119]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14


params [[2.5109847  4.9142247  2.23074953 2.76197628]
 [5.3972584  4.23272336 5.72451553 3.74147027]
 [1.48995922 5.62956656 4.96914749 2.79294082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.1973005  4.0921528  5.90633896 4.76829576]
 [3.85960056 6.17976677 0.37452829 3.13812537]
 [0.93780205 5.27608866 5.99577194 1.47328082]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[5.48047652 4.71504842 2.38779447 4.69031967]
 [0.53368208 2.26815573 0.85584838 3.36783596]
 [4.15557658 1.53675954 0.62502092 2.10135598]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
com

params [[3.15141421 0.81849292 3.37373702 0.34855704]
 [1.9723876  1.09331173 3.65947024 5.77420846]
 [5.81709814 1.20573762 2.83537604 1.185955  ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[2.00522324 4.37238962 1.98754202 4.4137233 ]
 [1.70406268 3.30780347 2.1820573  2.10108599]
 [1.11143794 4.59288688 1.38247111 3.73572936]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
399 [65, 67, 109] -1.1266988216513705 0.27486780285835266
params [[5.53253876 0.64563503 2.48035477 1.76872739]
 [2.52680993 4.96992397 3.61739658 5.97272355]
 [4.92114009 5.1348117  2.52972092 1.65682695]]
compile idx  0
compile idx  1
compi

compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
403 [43, 86, 64] -1.1266988216513705 -0.1994134783744812
params [[1.39386228 1.45258834 4.06715637 2.66752681]
 [0.66452493 0.04733511 2.66576474 3.28841585]
 [1.27913256 1.98143733 0.14805772 2.01577153]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.87734782 3.19153959 0.75216797 2.30672167]
 [5.96571498 4.53394149 2.05942221 2.66301848]
 [1.73680491 4.97824416 3.81225584 3.96514792]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[0.4353

compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
408 [90, 109, 29] -1.1266988216513705 -0.5160077214241028
params [[1.66444565 2.68774882 0.38866153 3.44284514]
 [2.64512358 5.10468301 1.38801571 0.50433468]
 [0.99017472 3.07995464 1.64419564 1.8851255 ]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14
params [[1.5272134  4.43818284 1.00316574 5.84281865]
 [2.21975174 4.90565054 0.75795775 5.44891102]
 [3.83375937 5.71536015 3.84436226 2.45871601]]
compile idx  0
compile idx  1
compile idx  2
compile idx  3
compile idx  4
compile idx  5
compile idx  6
compile idx  7
compile idx  8
compile idx  9
compile idx  10
compile idx  11
compile idx  12
compile idx  13
compile idx  14

KeyboardInterrupt: 

In [ ]:
plt.plot(timeList, range(len(timeList)))
plt.xlabel("time(s)")
plt.ylabel("epoch size")

In [ ]:
result = {}
for i_iter in range(n_search):
    circList = []
    compiledCircList = []
    weightList = []
    selectedAIdList = np.random.randint(0, len(NAS_search_space), (n_layers,)).tolist()
    
    fciE = initCircuit(distance, selectedAIdList)
    
#     find optimal expert
    for i in range(n_experts):
        # get params
        params = []
        min_loss = 100000
        min_expert_id = 0
        params = modelParam.get_params(selectedAIdList, i)

        # calculate
        exp = 0
        for idx, compiledCirc in enumerate(compiledCircList):   
            exp += compiledCirc(modelParam.params).real*weightList[idx].real
        loss = exp
        if loss<min_loss:
            min_loss = loss
            min_expert_id = i
    expert_idx = min_expert_id
    # get params
    params = []
    params = modelParam.get_params(selectedAIdList, expert_idx) 
    
    # for each set
    exp = 0
    for idx, compiledCirc in enumerate(compiledCircList):   
        exp += compiledCirc(modelParam.params).real*weightList[idx].real
        pass

        
        
#     print(params)
    print(i_iter, selectedAIdList, fciE, exp.item())
    
    result['-'.join([str(x) for x in selectedAIdList])] = min_loss
    
time_end=time.time()

In [ ]:
print(time.time()-time_start)

In [ ]:
# result = {}
# print(n_search)
# for i_iter in range(n_search):
#     selectedAIdList = np.random.randint(0, len(NAS_search_space), (n_layers,)).tolist()
#     circList = []
#     compiledCircList = []
#     weightList = []
#     fciE = initCircuit(distance, selectedAIdList)
#     for i in range(n_experts):
# #         print(i)
#         # get params
#         params = []
#         min_loss = 100000
#         min_expert_id = 0
#         for j in range(n_layers):
#             r_idx = selectedAIdList[j] // len(CNOTs_space)
#             params.append(params_space[i, j, r_idx:r_idx+1])
#         params = torch.tensor(np.concatenate(params, axis=0), requires_grad=False)  

#         # calculate
#         exp = 0
#         for idx, compiledCirc in enumerate(compiledCircList):   
#             exp += compiledCirc(params).real*weightList[idx].real
# #     print(exp)
#         loss = exp
#         if loss<min_loss:
#             min_loss = loss
#             min_expert_id = i
#     print(i_iter, selectedAIdList, min_loss)
#     result['-'.join([str(x) for x in selectedAIdList])] = min_loss
    


In [ ]:
sorted_result = list(result.items())
sorted_result.sort(key=lambda x: x[1], reverse=True)
for idx, data in enumerate(sorted_result):
    print(idx, data[0],data[1].item())